# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.ngcImagePullSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-secret  # name expected by NIMs
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "slim-gest.ngcImagePullSecret" . }}
{{- end }}


{{ if and .Values.ngcApiSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-api  # Name expected by NIMs
type: Opaque
stringData:
  NGC_CLI_API_KEY: {{ template "slim-gest.ngcApiSecret" . }}
  NGC_API_KEY: {{ template "slim-gest.ngcApiSecret" . }}
{{- end }}